# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['slashco.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icon.ico', '.'),
        ('locations.json', '.'),
        ('cover.png', '.'),
        ('admin_helper.py', '.'),
        ('sponsors.txt', '.'),
        ('tools/mitmdump.exe', 'tools'),
        ('tools/cleanup_hosts.py', 'tools'),
        ('tools/reset_network.py', 'tools'),
    ],
    hiddenimports=[
        'cryptography',
        'PIL',
        'Pillow',
        'PIL.ImageTk',
        'PIL.Image',
        'numpy',
        'tkinter',
        'http.server',
        'ssl',
        'json',
        'threading',
        'concurrent.futures',
        'mitmproxy',
        'mitmproxy.tools.dump',
        'mitmproxy.tools.main',
        'brotli',
        'zstandard',
        'kaitaistruct',
        'msgpack',
        'pyserial',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SlashCoSense',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
